version: "3.7"
services:
  engine:
    build:
      context: ../
      dockerfile: app/engine/Dockerfile
    restart: always
    volumes:
      - ../storage:/home/comely-io/engine/storage
      - ../tmp:/home/comely-io/engine/tmp
      - ../log/engine:/home/comely-io/engine/log
    env_file:
      - config.env
    networks:
      comely-app-net:
        ipv4_address: 10.0.20.11
  admin:
    build:
      context: ../
      dockerfile: app/admin/Dockerfile
    restart: always
    volumes:
      - ../app/admin/templates/default/knit:/home/comely-io/admin/template
      - ../app/admin/templates/default/www:/home/comely-io/admin/www/default
      - ../log/admin:/home/comely-io/admin/log
      - ../storage:/home/comely-io/admin/storage
      - ../tmp:/home/comely-io/admin/tmp
    environment:
      COMELY_APP_DEBUG: 1
      COMELY_APP_CACHED_CONFIG: "true"
    env_file:
      - config.env
    ports:
      - "${ADMIN_PORT}:6000"
    networks:
      comely-app-net:
        ipv4_address: 10.0.20.12
  api:
    build:
      context: ../
      dockerfile: app/api/Dockerfile
    restart: always
    volumes:
      - ../log/api:/home/comely-io/api/log
      - ../storage:/home/comely-io/api/storage
      - ../tmp:/home/comely-io/api/tmp
    environment:
      COMELY_APP_CACHED_CONFIG: "true"
    env_file:
      - config.env
    ports:
      - "${API_PORT}:6000"
    networks:
      comely-app-net:
        ipv4_address: 10.0.20.13

# Networks Configuration
networks:
  comely-app-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.20.0/27
